using PowerPointAddIn1.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PowerPointAddIn1.Forms
{
    public partial class QuestionSelectionForm : Form
    {
        public int SelectedIndex { get; private set; } = 0;
        private List<Question> _questions;

        public ListBox listBoxQuestions;
        public Button btnOK;
        public Button btnCancel;

        public QuestionSelectionForm(List<Question> questions)
        {
            InitializeComponent();
            _questions = questions;
            SetupForm();
        }

        private void SetupForm()
        {
            this.Text = "Select Question";
            this.Size = new System.Drawing.Size(400, 300);

            foreach (var question in _questions)
            {
                listBoxQuestions.Items.Add($"{question.Content} ({question.Points} pts)");
            }

            if (listBoxQuestions.Items.Count > 0)
                listBoxQuestions.SelectedIndex = 0;
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            SelectedIndex = listBoxQuestions.SelectedIndex;
            this.DialogResult = DialogResult.OK;
            this.Close();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
            this.Close();
        }

       /* private void InitializeComponent()
        {
            // Auto-generated by designer
        }*/

        private void QuestionSelectionForm_Load(object sender, EventArgs e)
        {

        }
    }
}
